### ISSUE TITLE
Swift-2.0

### ISSUE THREAD

**Issue by dskatz22** [lsolniczek/string-in-chain#4]
can you create a swift 2.0 branch with the new syntax changes?

**Comment by lsolniczek** [comment]
Hi, what new syntax do you mean?

**Comment by dskatz22** [comment]
Xcode 7 beta 5 is complaining about # in method args

**Comment by lsolniczek** [comment]
Sytax has been updated. Now it should work fine. All you have to do is update pod to '0.3.0'
